Repository woaine/calcifer, pull requests merged in 2025-04, with the labels that each got.

#1 Add External Dataset Files and Clean Them for Analysis
  .env.example
  .gitignore
  data/external/FLIR_group1.csv
  data/external/FLIR_group2.csv
  data/external/FLIR_groups1and2.csv
  data/external/ICI_group1.csv
  data/external/ICI_group2.csv
  data/external/ICI_groups1and2.csv
  data/external/LICENSE.txt
  data/external/README.md
  data/external/SHA256SUMS.txt
  data/external/_Figure1.png
  data/external/_Table1.pdf
  data/external/_Table2.pdf
  data/interim/cleaned_external_data.csv
  notebooks/data_cleaning.ipynb
  src/data/__init__.py
  src/data/cleaning.py
Labels: enhancement

#3 Implement Feature Engineering for Context-wise Data
  src/features/__init__.py
  src/features/feature_engineering.py
Labels: feat

#4 Enhance EDA with outlier detection and correlation analysis on preprocessed dataset
  .gitignore
  data/interim/preprocessed_external_data.csv
  notebooks/eda.ipynb
  reports/figures/correlation_matrix_cleaned.png
  reports/figures/correlation_matrix_preprocessed.png
  reports/figures/number_of_records_based_on_tg_segments.png
  reports/figures/scatter_plot_matrix_cleaned.png
  reports/figures/scatter_plot_matrix_preprocessed.png
  reports/figures/scatter_plot_with_regression_lines.png
  reports/figures/scatter_plot_with_regression_lines_cleaned.png
  reports/figures/scatter_plot_with_regression_lines_preprocessed.png
  src/eda/__init__.py
  src/eda/correlation_analysis.py
  src/eda/correlation_analysis_preprocess.py
  src/eda/distribution_analysis.py
  src/eda/outlier_analysis.py
Labels: feat

#7 Implementation of Superresolution REALESRGAN
  requirements.txt
  src/superresolution/__init__.py
  src/superresolution/realesrgan_model.py
Labels: feat

#8 Data Augmentation of the Cleaned External Dataset
  data/interim/augmented_data.csv
  reports/results/augmentation_performance.txt
Labels: feat

#9 Correction of Column Names
  data/interim/augmented_data.csv
Labels: fix

#10 Preprocessing on Augmented Data
  data/interim/preprocessed_augmented_data.csv
  notebooks/eda.ipynb
Labels: feat

#14 Train Best Models for Deployment
  models/mlp/normalized/non_engineered/non_processed/augmented/best_model.keras
  models/mlp/normalized/non_engineered/non_processed/augmented/fs.pkl
  models/mlp/normalized/non_engineered/non_processed/augmented/ts.pkl
  models/mlp/normalized/non_engineered/non_processed/external/best_model.keras
  models/mlp/normalized/non_engineered/non_processed/external/fs.pkl
  models/mlp/normalized/non_engineered/non_processed/external/ts.pkl
  models/mlp/normalized/non_engineered/preprocessed/augmented/best_model.keras
  models/mlp/normalized/non_engineered/preprocessed/augmented/fs.pkl
  models/mlp/normalized/non_engineered/preprocessed/augmented/ts.pkl
  models/mlp/normalized/non_engineered/preprocessed/external/best_model.keras
  models/mlp/normalized/non_engineered/preprocessed/external/fs.pkl
  models/mlp/normalized/non_engineered/preprocessed/external/ts.pkl
  models/mlp/standardized/non_engineered/non_processed/augmented/best_model.keras
  models/mlp/standardized/non_engineered/non_processed/augmented/fs.pkl
  models/mlp/standardized/non_engineered/non_processed/augmented/ts.pkl
  models/mlp/standardized/non_engineered/non_processed/external/best_model.keras
  models/mlp/standardized/non_engineered/non_processed/external/fs.pkl
  models/mlp/standardized/non_engineered/non_processed/external/ts.pkl
  models/mlp/standardized/non_engineered/preprocessed/augmented/best_model.keras
  models/mlp/standardized/non_engineered/preprocessed/augmented/fs.pkl
  models/mlp/standardized/non_engineered/preprocessed/augmented/ts.pkl
  models/mlp/standardized/non_engineered/preprocessed/external/best_model.keras
  models/mlp/standardized/non_engineered/preprocessed/external/fs.pkl
  models/mlp/standardized/non_engineered/preprocessed/external/ts.pkl
  reports/results/training/normalized/non_engineered/non_processed/augmented/best_model_training.csv
  reports/results/training/normalized/non_engineered/non_processed/augmented/conf.csv
  reports/results/training/normalized/non_engineered/non_processed/external/best_model_training.csv
  reports/results/training/normalized/non_engineered/non_processed/external/conf.csv
  reports/results/training/normalized/non_engineered/preprocessed/augmented/best_model_training.csv
  reports/results/training/normalized/non_engineered/preprocessed/augmented/conf.csv
  reports/results/training/normalized/non_engineered/preprocessed/external/best_model_training.csv
  reports/results/training/normalized/non_engineered/preprocessed/external/conf.csv
  reports/results/training/standardized/non_engineered/non_processed/augmented/best_model_training.csv
  reports/results/training/standardized/non_engineered/non_processed/augmented/conf.csv
  reports/results/training/standardized/non_engineered/non_processed/external/best_model_training.csv
  reports/results/training/standardized/non_engineered/non_processed/external/conf.csv
  reports/results/training/standardized/non_engineered/preprocessed/augmented/best_model_training.csv
  reports/results/training/standardized/non_engineered/preprocessed/augmented/conf.csv
  reports/results/training/standardized/non_engineered/preprocessed/external/best_model_training.csv
  reports/results/training/standardized/non_engineered/preprocessed/external/conf.csv
  src/models/mlp_deploy.py
Labels: feat
